/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public class Aio {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Aio(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Aio obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mraaJNI.delete_Aio(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Aio(int pin) {
    this(mraaJNI.new_Aio(pin), true);
  }

  public long read() {
    return mraaJNI.Aio_read(swigCPtr, this);
  }

  public float readFloat() {
    return mraaJNI.Aio_readFloat(swigCPtr, this);
  }

  public Result setBit(int bits) {
    return Result.swigToEnum(mraaJNI.Aio_setBit(swigCPtr, this, bits));
  }

  public int getBit() {
    return mraaJNI.Aio_getBit(swigCPtr, this);
  }

}
