/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public final class Dir {
  public final static Dir DIR_OUT = new Dir("DIR_OUT", mraaJNI.DIR_OUT_get());
  public final static Dir DIR_IN = new Dir("DIR_IN", mraaJNI.DIR_IN_get());
  public final static Dir DIR_OUT_HIGH = new Dir("DIR_OUT_HIGH", mraaJNI.DIR_OUT_HIGH_get());
  public final static Dir DIR_OUT_LOW = new Dir("DIR_OUT_LOW", mraaJNI.DIR_OUT_LOW_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Dir swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Dir.class + " with value " + swigValue);
  }

  private Dir(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Dir(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Dir(String swigName, Dir swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Dir[] swigValues = { DIR_OUT, DIR_IN, DIR_OUT_HIGH, DIR_OUT_LOW };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

