/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public final class Edge {
  public final static Edge EDGE_NONE = new Edge("EDGE_NONE", mraaJNI.EDGE_NONE_get());
  public final static Edge EDGE_BOTH = new Edge("EDGE_BOTH", mraaJNI.EDGE_BOTH_get());
  public final static Edge EDGE_RISING = new Edge("EDGE_RISING", mraaJNI.EDGE_RISING_get());
  public final static Edge EDGE_FALLING = new Edge("EDGE_FALLING", mraaJNI.EDGE_FALLING_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Edge swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Edge.class + " with value " + swigValue);
  }

  private Edge(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Edge(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Edge(String swigName, Edge swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Edge[] swigValues = { EDGE_NONE, EDGE_BOTH, EDGE_RISING, EDGE_FALLING };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

