/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public final class Mode {
  public final static Mode MODE_STRONG = new Mode("MODE_STRONG", mraaJNI.MODE_STRONG_get());
  public final static Mode MODE_PULLUP = new Mode("MODE_PULLUP", mraaJNI.MODE_PULLUP_get());
  public final static Mode MODE_PULLDOWN = new Mode("MODE_PULLDOWN", mraaJNI.MODE_PULLDOWN_get());
  public final static Mode MODE_HIZ = new Mode("MODE_HIZ", mraaJNI.MODE_HIZ_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Mode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Mode.class + " with value " + swigValue);
  }

  private Mode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Mode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Mode(String swigName, Mode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Mode[] swigValues = { MODE_STRONG, MODE_PULLUP, MODE_PULLDOWN, MODE_HIZ };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

