/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public final class Platform {
  public final static Platform INTEL_GALILEO_GEN1 = new Platform("INTEL_GALILEO_GEN1", mraaJNI.INTEL_GALILEO_GEN1_get());
  public final static Platform INTEL_GALILEO_GEN2 = new Platform("INTEL_GALILEO_GEN2", mraaJNI.INTEL_GALILEO_GEN2_get());
  public final static Platform INTEL_EDISON_FAB_C = new Platform("INTEL_EDISON_FAB_C", mraaJNI.INTEL_EDISON_FAB_C_get());
  public final static Platform INTEL_DE3815 = new Platform("INTEL_DE3815", mraaJNI.INTEL_DE3815_get());
  public final static Platform INTEL_MINNOWBOARD_MAX = new Platform("INTEL_MINNOWBOARD_MAX", mraaJNI.INTEL_MINNOWBOARD_MAX_get());
  public final static Platform RASPBERRY_PI = new Platform("RASPBERRY_PI", mraaJNI.RASPBERRY_PI_get());
  public final static Platform BEAGLEBONE = new Platform("BEAGLEBONE", mraaJNI.BEAGLEBONE_get());
  public final static Platform BANANA = new Platform("BANANA", mraaJNI.BANANA_get());
  public final static Platform INTEL_NUC5 = new Platform("INTEL_NUC5", mraaJNI.INTEL_NUC5_get());
  public final static Platform A96BOARDS = new Platform("A96BOARDS", mraaJNI.A96BOARDS_get());
  public final static Platform INTEL_SOFIA_3GR = new Platform("INTEL_SOFIA_3GR", mraaJNI.INTEL_SOFIA_3GR_get());
  public final static Platform INTEL_CHERRYHILLS = new Platform("INTEL_CHERRYHILLS", mraaJNI.INTEL_CHERRYHILLS_get());
  public final static Platform INTEL_UP = new Platform("INTEL_UP", mraaJNI.INTEL_UP_get());
  public final static Platform INTEL_JOULE_EXPANSION = new Platform("INTEL_JOULE_EXPANSION", mraaJNI.INTEL_JOULE_EXPANSION_get());
  public final static Platform PHYBOARD_WEGA = new Platform("PHYBOARD_WEGA", mraaJNI.PHYBOARD_WEGA_get());
  public final static Platform DE_NANO_SOC = new Platform("DE_NANO_SOC", mraaJNI.DE_NANO_SOC_get());
  public final static Platform FTDI_FT4222 = new Platform("FTDI_FT4222", mraaJNI.FTDI_FT4222_get());
  public final static Platform GENERIC_FIRMATA = new Platform("GENERIC_FIRMATA", mraaJNI.GENERIC_FIRMATA_get());
  public final static Platform NULL_PLATFORM = new Platform("NULL_PLATFORM", mraaJNI.NULL_PLATFORM_get());
  public final static Platform UNKNOWN_PLATFORM = new Platform("UNKNOWN_PLATFORM", mraaJNI.UNKNOWN_PLATFORM_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Platform swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Platform.class + " with value " + swigValue);
  }

  private Platform(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Platform(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Platform(String swigName, Platform swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Platform[] swigValues = { INTEL_GALILEO_GEN1, INTEL_GALILEO_GEN2, INTEL_EDISON_FAB_C, INTEL_DE3815, INTEL_MINNOWBOARD_MAX, RASPBERRY_PI, BEAGLEBONE, BANANA, INTEL_NUC5, A96BOARDS, INTEL_SOFIA_3GR, INTEL_CHERRYHILLS, INTEL_UP, INTEL_JOULE_EXPANSION, PHYBOARD_WEGA, DE_NANO_SOC, FTDI_FT4222, GENERIC_FIRMATA, NULL_PLATFORM, UNKNOWN_PLATFORM };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

