/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public class Pwm {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Pwm(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Pwm obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mraaJNI.delete_Pwm(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Pwm(int pin, boolean owner, int chipid) {
    this(mraaJNI.new_Pwm__SWIG_0(pin, owner, chipid), true);
  }

  public Pwm(int pin, boolean owner) {
    this(mraaJNI.new_Pwm__SWIG_1(pin, owner), true);
  }

  public Pwm(int pin) {
    this(mraaJNI.new_Pwm__SWIG_2(pin), true);
  }

  public Result write(float percentage) {
    return Result.swigToEnum(mraaJNI.Pwm_write(swigCPtr, this, percentage));
  }

  public float read() {
    return mraaJNI.Pwm_read(swigCPtr, this);
  }

  public Result period(float period) {
    return Result.swigToEnum(mraaJNI.Pwm_period(swigCPtr, this, period));
  }

  public Result period_ms(int ms) {
    return Result.swigToEnum(mraaJNI.Pwm_period_ms(swigCPtr, this, ms));
  }

  public Result period_us(int us) {
    return Result.swigToEnum(mraaJNI.Pwm_period_us(swigCPtr, this, us));
  }

  public Result pulsewidth(float seconds) {
    return Result.swigToEnum(mraaJNI.Pwm_pulsewidth(swigCPtr, this, seconds));
  }

  public Result pulsewidth_ms(int ms) {
    return Result.swigToEnum(mraaJNI.Pwm_pulsewidth_ms(swigCPtr, this, ms));
  }

  public Result pulsewidth_us(int us) {
    return Result.swigToEnum(mraaJNI.Pwm_pulsewidth_us(swigCPtr, this, us));
  }

  public Result enable(boolean enable) {
    return Result.swigToEnum(mraaJNI.Pwm_enable(swigCPtr, this, enable));
  }

  public int max_period() {
    return mraaJNI.Pwm_max_period(swigCPtr, this);
  }

  public int min_period() {
    return mraaJNI.Pwm_min_period(swigCPtr, this);
  }

}
