/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public final class Spi_Mode {
  public final static Spi_Mode SPI_MODE0 = new Spi_Mode("SPI_MODE0", mraaJNI.SPI_MODE0_get());
  public final static Spi_Mode SPI_MODE1 = new Spi_Mode("SPI_MODE1", mraaJNI.SPI_MODE1_get());
  public final static Spi_Mode SPI_MODE2 = new Spi_Mode("SPI_MODE2", mraaJNI.SPI_MODE2_get());
  public final static Spi_Mode SPI_MODE3 = new Spi_Mode("SPI_MODE3", mraaJNI.SPI_MODE3_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static Spi_Mode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + Spi_Mode.class + " with value " + swigValue);
  }

  private Spi_Mode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private Spi_Mode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private Spi_Mode(String swigName, Spi_Mode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static Spi_Mode[] swigValues = { SPI_MODE0, SPI_MODE1, SPI_MODE2, SPI_MODE3 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

