/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package mraa;

public final class UartParity {
  public final static UartParity UART_PARITY_NONE = new UartParity("UART_PARITY_NONE", mraaJNI.UART_PARITY_NONE_get());
  public final static UartParity UART_PARITY_EVEN = new UartParity("UART_PARITY_EVEN", mraaJNI.UART_PARITY_EVEN_get());
  public final static UartParity UART_PARITY_ODD = new UartParity("UART_PARITY_ODD", mraaJNI.UART_PARITY_ODD_get());
  public final static UartParity UART_PARITY_MARK = new UartParity("UART_PARITY_MARK", mraaJNI.UART_PARITY_MARK_get());
  public final static UartParity UART_PARITY_SPACE = new UartParity("UART_PARITY_SPACE", mraaJNI.UART_PARITY_SPACE_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static UartParity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + UartParity.class + " with value " + swigValue);
  }

  private UartParity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private UartParity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private UartParity(String swigName, UartParity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static UartParity[] swigValues = { UART_PARITY_NONE, UART_PARITY_EVEN, UART_PARITY_ODD, UART_PARITY_MARK, UART_PARITY_SPACE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

